spring.application.name=springSecurity
server.port=8084

# you not create user and password defult show terminal this type show it given below.
#Using generated security password: f6ea94e9-d71d-4b20-8edc-b349d0c612c3


spring.security.user.name=ranjit
spring.security.user.password=ranjit
